### ISSUE TITLE
Train with NHR sport 1 fail

### ISSUE THREAD

**Issue by taoistwar** [zju3dv/im4d#10]
command is 
```bash
python train_net.py --cfg_file configs/exps/im4d/nhr/sport1.yaml
```

error:

```
Traceback (most recent call last):
  File "/home/haima/im4d/train_net.py", line 108, in <module>
    main()
  File "/home/haima/im4d/train_net.py", line 100, in main
    train(cfg, network)
  File "/home/haima/im4d/train_net.py", line 22, in train
    train_loader = make_data_loader(cfg,
  File "/home/haima/im4d/lib/datasets/make_dataset.py", line 90, in make_data_loader
    dataset = make_dataset(cfg, is_train)
  File "/home/haima/im4d/lib/datasets/make_dataset.py", line 39, in make_dataset
    dataset = dataset(**args)
  File "/home/haima/im4d/lib/datasets/volcap/base_dataset.py", line 35, in __init__
    self.prepare_camera() # prepare camera intrinsics and extrinsics
  File "/home/haima/im4d/lib/datasets/volcap/base_dataset.py", line 68, in prepare_camera
    cams = easy_utils.read_camera(intri_path, extri_path, read_rvec=self.cfg.get('read_rvec', True))
  File "/home/haima/im4d/lib/utils/easyvv/easy_utils.py", line 73, in read_camera
    assert os.path.exists(intri_path), intri_path
AssertionError: /mnt/e/im4d/NHR/sport_1_easymocap/intri.yml
```

question:
1. NHR sport1 download from  [mlp_maps](https://github.com/zju3dv/mlp_maps/blob/master/INSTALL.md) , but miss intri.yml   
  from google: <https://drive.google.com/file/d/1BnqbXXzswcDh_3VzkYz1PW6LMWVf_HNv/view>

**Comment by haotongl** [comment]
Hi, please download the processed data from MLP_Maps instead of original data. 
![image](https://github.com/zju3dv/im4d/assets/45787711/d8f9c8a6-31e5-48d5-a77c-3f920980f443)
